name: Test Proyect
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: coge el codigo del repositorio
        uses: actions/checkout@v3
      - name: installar NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - nome: Instalar dependencies
        run: npm ci
      - nome:  Ejecutar tests
        run: npm test 